import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ko' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ko: {
    // Navigation
    'nav.home': '홈',
    'nav.woorijib': '우리집',
    'nav.eoullim': '어울림',
    'nav.bodab': '보답',
    'nav.nest': 'Nest',
    'nav.uniqdata': 'UniQdata',
    'nav.qtech': 'Q-Tech',
    'nav.vision': '비전',

    // Q-Tech Page
    'qtech.title': 'Q-Tech',
    'qtech.subtitle': 'SportiQue의 미래를 만드는 곳',
    'qtech.description': 'AI, IoT, 블록체인 기술로\n케어의 새로운 패러다임을 연구합니다',
    'qtech.achievement': '2025 한이음 드림업 - 돌봄 로봇 개발 완료',
    'qtech.mission': '우리의 미션',
    'qtech.mission.statement': '기술로 모든 세대가 더 건강하고 행복한 삶을 살 수 있도록',
    'qtech.research': '주요 연구 분야',
    'qtech.research.robot': '돌봄 로봇',
    'qtech.research.robot.desc': '어르신과 함께하는 스마트 반려 로봇',
    'qtech.research.blockchain': '블록체인',
    'qtech.research.blockchain.desc': 'XRPL 기반 안전한 건강 데이터 관리',
    'qtech.cta.title': '작은 기술로 큰 변화를',
    'qtech.cta.desc': '어르신들이 더 편하게 사용할 수 있는 기술을 연구합니다',

    // Home Page
    'home.hero.title.line1': '가족의 모든 세대를 잇는',
    'home.hero.title.line2': '건강한 연결고리',
    'home.hero.subtitle.line1': '20대부터 80대까지, 각 세대가 필요한 순간에',
    'home.hero.subtitle.line2': '가장 적절한 케어를 제공하는 생애주기 맞춤 플랫폼',
    'home.services.title': '세대별 맞춤 솔루션',
    'home.eoullim.age': '50-60대',
    'home.eoullim.title': '어울림',
    'home.eoullim.subtitle': '인생 2막',
    'home.eoullim.feature1': '또래와 함께하는 운동',
    'home.eoullim.feature2': '취미 활동과 동호회',
    'home.eoullim.feature3': '건강한 생활 습관',
    'home.bodab.age': '60-70대',
    'home.bodab.title': 'Bodab',
    'home.bodab.subtitle': '건강 관리',
    'home.bodab.feature1': '음성 인터페이스',
    'home.bodab.feature2': '복약 알림',
    'home.bodab.feature3': 'AI 건강 상담',
    'home.nest.age': '70대+',
    'home.nest.title': 'Nest',
    'home.nest.subtitle': '전문 케어',
    'home.nest.feature1': '24시간 전문 케어',
    'home.nest.feature2': '가족과 실시간 소통',
    'home.nest.feature3': '투명한 케어 기록',
    'home.uniqdata.title': '병원비, 이제 돌려받으세요',
    'home.uniqdata.subtitle': '검진받으며 쓴 돈, 그냥 버리지 마세요.\n내 의료 데이터 열람권 NFT를 판매하고 수익을 만드세요.',
    'home.uniqdata.age': '전 연령',
    'home.uniqdata.powered': 'Powered by XRPL',
    'home.uniqdata.platform': 'XRPL 기반 의료 데이터 NFT 마켓플레이스',
    'home.uniqdata.desc': '열람권을 NFT로 발행하여 안전하게 거래합니다',
    'home.uniqdata.feature1': '병원 검진 데이터를 UniQdata 데이터베이스에 안전하게 저장',
    'home.uniqdata.feature2': '내 데이터 열람권을 XRPL NFT로 발행',
    'home.uniqdata.feature3': '제약사·연구소에 열람권 NFT를 판매하고 XRP로 수익 창출',
    'home.uniqdata.feature4': '데이터는 안전하게 보관, 열람권만 거래',
    'home.vision.title': '생애 전주기 케어 플랫폼',
    'home.vision.subtitle': '한 번 시작하면 평생 함께하는 가족 건강 파트너.\n각 세대가 필요한 순간에 가장 적절한 케어를 제공합니다.',
    'home.vision.step1.title': '50-60대: 건강한 인생 2막',
    'home.vision.step1.desc': '어울림에서 또래와 함께 운동하며 건강한 노후를 준비합니다.',
    'home.vision.step2.title': '60-70대: 자립적 건강 관리',
    'home.vision.step2.desc': 'Bodab의 AI 헬스케어로 스스로 건강을 관리합니다.',
    'home.vision.step3.title': '70대+: 전문적인 케어',
    'home.vision.step3.desc': 'Nest에서 24시간 전문적인 케어를 받으며 편안한 노후를 보냅니다.',
    'home.vision.step4.title': '전 연령: 데이터 가치 실현',
    'home.vision.step4.desc': 'UniQdata로 의료 데이터를 안전하게 관리하고 수익을 창출합니다.',

    // Woorijib Page
    'woorijib.title': '우리집',
    'woorijib.subtitle': '가족만의 특별한 공간',
    'woorijib.desc': '접근성 향상을 위한 연구 프로젝트\n가족 소통의 새로운 패러다임 탐구',

    // Eoullim Page
    'eoullim.title': '어울림',
    'eoullim.subtitle': '인생 2막을 위한 특별한 공간',
    'eoullim.desc': '50-60대를 위한 프리미엄 피트니스 & 소셜 클럽\n건강한 몸과 마음, 그리고 새로운 친구들',

    // Nest Page
    'nest.title': 'Nest',
    'nest.subtitle': '따뜻한 보금자리, 전문적인 케어',
    'nest.desc': '70대 이상 어르신을 위한 프리미엄 요양 시설\n가족과 함께하는 투명한 케어 시스템',

    // Vision Page
    'vision.title': '우리가 바라보는 가족',
    'vision.subtitle': '부모님을 걱정하는 자녀의 마음,\n자녀에게 짐이 되고 싶지 않은 부모님의 마음,\n우리는 그 두 마음을 모두 이해합니다.',
    'vision.cta': '지금 시작하세요',
    'vision.cta.desc': '연령대별 맞춤 서비스를 선택하세요',

    // Hero Section
    'hero.title.line1': 'Sportique의 두 가지 서비스로',
    'hero.title.line2': '건강한 미래를 만듭니다',
    'hero.subtitle.line1': '보답(Bodab)으로 AI 헬스케어를 경험하고',
    'hero.subtitle.line2': 'UniqData에서 데이터 주권을 실현하세요',
    'hero.cta.start': '시작하기',
    'hero.cta.learn': '자세히 보기',

    // Features Section
    'features.title': '보답(Bodab)의 핵심 기능',
    'features.subtitle': 'AI와 블록체인이 만드는 혁신적인 헬스케어 솔루션',
    'features.step': 'STEP',
    'features.1.title': 'AI 건강 분석',
    'features.1.desc': 'RAG 기반 AI가 과거 진료기록을 분석하여 맞춤형 건강 상담을 제공합니다',
    'features.2.title': '실시간 모니터링',
    'features.2.desc': '웨어러블 기기와 IoT를 통해 24시간 생체신호를 모니터링합니다',
    'features.3.title': '블록체인 보안',
    'features.3.desc': 'XRPL 네트워크에 건강 데이터를 안전하게 저장하고 소유권을 보장합니다',
    'features.4.title': '데이터 수익화',
    'features.4.desc': '건강 데이터 제공 시 XRP로 즉시 보상을 받을 수 있습니다',

    // About Section
    'about.title': 'About Sportique',
    'about.ecosystem': 'Sportique의 통합 헬스케어 생태계',
    'about.ecosystem.desc': '보답(Bodab)에서 수집한 건강 데이터가 UniqData로 연결되어 데이터 주권과 수익화를 실현합니다. AI 헬스케어와 블록체인 기술이 만나 건강한 글로벌 사회를 만들어갑니다.',
    'about.check1': 'AI 기반 시니어 케어 솔루션 (보답)',
    'about.check2': '글로벌 데이터 마켓플레이스 (UniqData)',
    'about.check3': 'XRPL 블록체인 기반 데이터 보안',
    'about.vision.title': '우리의 비전',
    'about.vision.desc': '모든 사람이 자신의 건강 데이터를 소유하고, 그 데이터로부터 공정한 보상을 받을 수 있는 건강한 디지털 사회를 만들어갑니다.',

    // Services Section
    'services.title': 'Our Services',
    'services.subtitle': 'Sportique가 제공하는 두 가지 독립적인 서비스',
    'services.bodab.title': '보답 (Bodab)',
    'services.bodab.desc': 'AI 기반 실버 헬스케어 앱으로 데이터 측정과 건강 분석을 통한 맞춤형 시니어 케어를 제공합니다',
    'services.bodab.feature1': 'AI 건강 분석',
    'services.bodab.feature2': '실시간 데이터 측정',
    'services.bodab.feature3': '시니어 케어 솔루션',
    'services.bodab.cta': '자세히 보기',
    'services.uniqdata.title': 'UniqData',
    'services.uniqdata.desc': '글로벌 데이터 마켓플레이스로 건강데이터 주권을 실현하고 NFT와 영지식 증명으로 수익화합니다',
    'services.uniqdata.feature1': '데이터 주권 실현',
    'services.uniqdata.feature2': 'NFT 기반 소유권 증명',
    'services.uniqdata.feature3': '데이터 수익화',
    'services.uniqdata.cta': 'UniqData 방문하기',

    // Rewards Section
    'rewards.title': '보답 (Bodab)',
    'rewards.desc': 'AI 기반 실버 헬스케어 앱으로 데이터 측정과 건강 분석을 통한 맞춤형 시니어 케어를 제공합니다',
    'rewards.connection': '수집된 건강 데이터는 UniqData로 전송되어 데이터 주권과 수익화의 기반이 됩니다',
    'rewards.feature1.title': 'AI 건강 분석',
    'rewards.feature1.desc': 'RAG 기반 의료 상담, 과거 진료기록 분석, 맞춤형 건강 추천',
    'rewards.feature2.title': '실시간 데이터 측정',
    'rewards.feature2.desc': '웨어러블 기기 연동, 24/7 생체신호 모니터링, 건강 상태 추적',
    'rewards.feature3.title': '시니어 케어 솔루션',
    'rewards.feature3.desc': '고령화 시대 맞춤 돌봄, 응급상황 대응, 가족 안심 서비스',
    'rewards.cta': '자세히 보기',

    // XRPL Section
    'xrpl.title': 'UniqData 글로벌 마켓플레이스',
    'xrpl.desc': 'uniqdata.io에서 보답에서 수집한 건강데이터의 주권을 실현하고 NFT와 영지식 증명을 통한 데이터 익명화, 이전 및 판매로 나의 데이터로 수익을 만들 수 있습니다',
    'xrpl.connection': '보답(Bodab)에서 생성된 건강 데이터가 UniqData에서 안전하게 관리되고 수익화됩니다',
    'xrpl.feature1': '건강데이터 주권 실현',
    'xrpl.feature2': 'NFT 기반 데이터 소유권 증명',
    'xrpl.feature3': '영지식 증명을 통한 익명화',
    'xrpl.feature4': '데이터 이전 및 판매로 수익 창출',
    'xrpl.cta': 'UniqData 방문하기',
    'xrpl.card.title': 'UniqData.io',
    'xrpl.card.subtitle': '글로벌 데이터 마켓플레이스',

    // Partners Section
    'partners.title': '파트너십',
    'partners.subtitle': '혁신적인 헬스케어 생태계를 함께 만들어갑니다',
    'partners.hoseo.name': '호서대학교',
    'partners.hoseo.type': '학술 파트너',
    'partners.hoseo.desc': 'AI 헬스케어 연구 협력',
    'partners.xrpl.name': 'XRPL Foundation',
    'partners.xrpl.type': '기술 파트너',
    'partners.xrpl.desc': '블록체인 기술 지원',
    'partners.medical.name': '의료기관',
    'partners.medical.type': '의료 파트너',
    'partners.medical.desc': '진료 데이터 연동',
    'partners.wearable.name': '웨어러블 기업',
    'partners.wearable.type': '하드웨어 파트너',
    'partners.wearable.desc': 'IoT 기기 연동',
    'partners.insurance.name': '보험사',
    'partners.insurance.type': '비즈니스 파트너',
    'partners.insurance.desc': '헬스케어 보험 연계',
    'partners.government.name': '정부기관',
    'partners.government.type': '정책 파트너',
    'partners.government.desc': '디지털 헬스케어 정책',

    // Footer
    'footer.description': 'XRPL 기반 블록체인 기술로 데이터주권을 되찾고, AI 기반 헬스케어 솔루션을 제공하는 플랫폼입니다.',
    'footer.services': '서비스',
    'footer.bodab': '보답 (Bodab)',
    'footer.uniqdata': 'UniqData',
    'footer.xrpl': 'XRPL',
    'footer.company': '회사',
    'footer.about': '소개',
    'footer.careers': '채용',
    'footer.partnership': '파트너십',
    'footer.support': '지원',
    'footer.customer': '고객센터',
    'footer.faq': 'FAQ',
    'footer.contact': '문의하기',
    'footer.copyright': '© 2025 Sportique. All rights reserved.',
    'footer.privacy': '개인정보처리방침',
    'footer.terms': '이용약관',

    // Bodab Page
    'bodab.page.subtitle': '60-70대 어르신을 위한 자립적 건강 관리 플랫폼',
    'bodab.page.desc': '큰 글씨와 음성 인터페이스로 쉽게 사용할 수 있는 건강 관리 서비스입니다',
    'bodab.features.title': 'Bodab의 핵심 기능',
    'bodab.features.voice.title': '음성 인터페이스',
    'bodab.features.voice.desc': '복잡한 터치 없이 말로 모든 기능을 사용할 수 있습니다',
    'bodab.features.medication.title': '복약 관리',
    'bodab.features.medication.desc': '약 복용 시간을 알려주고 복약 기록을 자동으로 관리합니다',
    'bodab.features.health.title': '건강 기록',
    'bodab.features.health.desc': '혈압, 혈당 등 건강 수치를 쉽게 기록하고 관리합니다',
    'bodab.features.hospital.title': '병원 예약',
    'bodab.features.hospital.desc': '진료 예약과 병원 방문 일정을 한눈에 확인합니다',
    'bodab.features.family.title': '가족 공유',
    'bodab.features.family.desc': '건강 정보를 가족과 안전하게 공유합니다',
    'bodab.features.sos.title': '응급 SOS',
    'bodab.features.sos.desc': '위급 상황 시 빠르게 도움을 요청할 수 있습니다',
    'bodab.ai.title': 'AI 건강 비서',
    'bodab.ai.desc': '24시간 대화 가능한 AI 건강 비서가 어르신의 건강을 챙겨드립니다.',
    'bodab.ai.consultation.title': '건강 상담',
    'bodab.ai.consultation.desc': '증상을 말하면 AI가 적절한 조언을 제공합니다',
    'bodab.ai.conversation.title': '일상 대화',
    'bodab.ai.conversation.desc': '외로울 때 언제든 대화 상대가 되어드립니다',
    'bodab.ai.coaching.title': '건강 습관 코칭',
    'bodab.ai.coaching.desc': '건강한 생활 습관을 만들도록 도와드립니다',
    'bodab.ai.quote1': '"오늘 약은 드셨나요?"',
    'bodab.ai.quote2': '"혈압 측정하실 시간입니다"',
    'bodab.simple.title': '쉽고 간단한 사용법',
    'bodab.simple.large.title': '큰 글씨',
    'bodab.simple.large.desc': '모든 글씨가 크고 선명해서 잘 보입니다',
    'bodab.simple.voice.title': '음성 명령',
    'bodab.simple.voice.desc': '말로 조작할 수 있습니다',
    'bodab.simple.simple.title': '간단한 구성',
    'bodab.simple.simple.desc': '필요한 기능만 크고 명확하게 배치했습니다',
    'bodab.cta.title': '건강 관리가 필요할 때, 자립적으로 케어',
    'bodab.cta.desc': 'Bodab과 함께 건강한 노후를 스스로 관리하세요',
    'bodab.cta.button': '무료 체험 시작하기',

    // Nest Page
    'nest.features.title': 'Nest만의 특별함',
    'nest.features.care24.title': '24시간 전문 케어',
    'nest.features.care24.desc': '의료진과 요양보호사가 24시간 상주하며 어르신을 케어합니다',
    'nest.features.family.title': '가족과 실시간 소통',
    'nest.features.family.desc': '일일 케어 리포트와 화상통화로 가족과 매일 연결됩니다',
    'nest.features.home.title': '따뜻한 보금자리',
    'nest.features.home.desc': '집처럼 편안하고 안전한 환경에서 생활하실 수 있습니다',
    'nest.features.record.title': '투명한 케어 기록',
    'nest.features.record.desc': '모든 케어 내용이 투명하게 기록되고 가족에게 공유됩니다',
    'nest.system.title': '전문적인 케어 시스템',
    'nest.system.medical.title': '의료진 상주',
    'nest.system.medical.desc': '전문 의료진이 24시간 건강 상태를 모니터링합니다',
    'nest.system.custom.title': '맞춤형 케어 플랜',
    'nest.system.custom.desc': '개인별 건강 상태에 맞는 맞춤 케어를 제공합니다',
    'nest.system.rehab.title': '재활 프로그램',
    'nest.system.rehab.desc': '전문 재활 프로그램으로 건강 회복을 돕습니다',
    'nest.system.emotional.title': '정서적 케어',
    'nest.system.emotional.desc': '다양한 프로그램으로 정서적 안정을 제공합니다',
    'nest.system.quote1': '따뜻한 보금자리',
    'nest.system.quote2': '전문적인 케어',
    'nest.cta.title': '부모님을 위한 최선의 선택',
    'nest.cta.desc': 'Nest와 함께 부모님께 편안하고 행복한 노후를 선물하세요',
    'nest.cta.button': '상담 신청하기',

    // Eoullim Page
    'eoullim.programs.title': '맞춤형 프로그램',
    'eoullim.programs.yoga.title': '시니어 요가',
    'eoullim.programs.yoga.desc': '관절에 무리 없는 부드러운 동작으로 유연성과 균형감각 향상',
    'eoullim.programs.aqua.title': '아쿠아로빅',
    'eoullim.programs.aqua.desc': '물속에서 즐기는 전신 운동, 관절 부담 최소화',
    'eoullim.programs.walking.title': '걷기 모임',
    'eoullim.programs.walking.desc': '동네 공원에서 함께하는 건강한 걷기 운동',
    'eoullim.programs.dance.title': '댄스 클래스',
    'eoullim.programs.dance.desc': '즐거운 음악과 함께하는 실버 댄스',
    'eoullim.programs.strength.title': '근력 운동',
    'eoullim.programs.strength.desc': '안전한 기구를 활용한 근력 강화 프로그램',
    'eoullim.programs.meditation.title': '명상 & 스트레칭',
    'eoullim.programs.meditation.desc': '마음과 몸의 균형을 찾는 힐링 프로그램',
    'eoullim.community.title': '함께하는 커뮤니티',
    'eoullim.community.desc': '또래와 함께 운동하며 새로운 친구를 만나고, 건강한 생활 습관을 만들어갑니다.',
    'eoullim.community.trainer': '전문 트레이너의 안전한 지도',
    'eoullim.community.custom': '연령별 맞춤 운동 프로그램',
    'eoullim.community.tea': '운동 후 건강한 차 모임',
    'eoullim.community.check': '월별 건강 체크 및 상담',
    'eoullim.community.quote': '건강한 인생 2막을 시작하세요',
    'eoullim.cta.title': '건강한 인생 2막을 시작하세요',
    'eoullim.cta.desc': '지금 가입하시면 첫 달 50% 할인',
    'eoullim.cta.button': '무료 체험 신청하기',

    // Woorijib Page
    'woorijib.features.title': '주요 기능',
    'woorijib.features.messenger.title': '가족 전용 메신저',
    'woorijib.features.messenger.desc': '광고 없는 깨끗한 가족 소통 공간',
    'woorijib.features.album.title': '자동 앨범 정리',
    'woorijib.features.album.desc': 'AI가 자동으로 사진과 동영상을 정리',
    'woorijib.features.schedule.title': '가족 일정 공유',
    'woorijib.features.schedule.desc': '중요한 가족 일정을 함께 관리',
    'woorijib.features.parent.title': '부모님 모드',
    'woorijib.features.parent.desc': '큰 글씨와 간편한 인터페이스',
    'woorijib.features.health.title': '건강 체크',
    'woorijib.features.health.desc': '가족 구성원의 건강 상태 확인',
    'woorijib.features.privacy.title': '프라이버시 보장',
    'woorijib.features.privacy.desc': '가족 데이터의 안전한 보호',
    'woorijib.cta.title': '접근성 향상 연구 프로젝트',
    'woorijib.cta.desc': '가족 소통의 새로운 미래를 함께 만들어갑니다',
    'woorijib.cta.button': '프로젝트 참여하기',

    // UniqData Page
    'uniqdata.page.title': 'XRPL 기반 의료 데이터 NFT 마켓플레이스',
    'uniqdata.page.desc': '데이터는 안전하게 저장하고, 열람권을 NFT로 발행하여 거래합니다',
    'uniqdata.page.powered': 'Powered by XRPL',
    'uniqdata.features.title': 'UniQdata의 혁신적 기능',
    'uniqdata.features.storage.title': '안전한 데이터 저장',
    'uniqdata.features.storage.desc': '의료 데이터를 UniQdata DB에 안전하게 보관합니다',
    'uniqdata.features.nft.title': '열람권 NFT 발행',
    'uniqdata.features.nft.desc': '데이터 열람권을 XRPL NFT로 발행하여 소유권을 증명합니다',
    'uniqdata.features.revenue.title': 'NFT 판매 수익',
    'uniqdata.features.revenue.desc': '열람권 NFT를 제약사·연구소에 판매하고 XRP로 수익 창출',
    'uniqdata.how.title': '어떻게 작동하나요?',
    'uniqdata.how.step1.title': '데이터 저장',
    'uniqdata.how.step1.desc': '의료 데이터를 UniQdata 데이터베이스에 안전하게 저장',
    'uniqdata.how.step2.title': 'NFT 발행',
    'uniqdata.how.step2.desc': '데이터 열람권을 XRPL NFT로 발행',
    'uniqdata.how.step3.title': 'NFT 판매',
    'uniqdata.how.step3.desc': '제약사·연구소에 열람권 NFT를 판매',
    'uniqdata.how.step4.title': 'XRP 수익',
    'uniqdata.how.step4.desc': 'NFT 판매 대금을 XRP로 즉시 정산',
    'uniqdata.benefits.title': '데이터가 돈이 되는 시대',
    'uniqdata.benefits.desc': '그동안 무료로 제공했던 당신의 의료 데이터,\n이제는 UniQdata를 통해 정당한 대가를 받으세요.',
    'uniqdata.benefits.transparent.title': '투명한 NFT 거래',
    'uniqdata.benefits.transparent.desc': 'XRPL 블록체인으로 모든 NFT 거래가 투명하게 기록됩니다',
    'uniqdata.benefits.safe.title': '데이터는 안전하게 보관',
    'uniqdata.benefits.safe.desc': '원본 데이터는 UniQdata DB에 안전하게 저장되고, 열람권만 거래됩니다',
    'uniqdata.benefits.instant.title': '즉시 정산 시스템',
    'uniqdata.benefits.instant.desc': 'NFT가 판매되면 XRP로 즉시 정산됩니다',
    'uniqdata.benefits.stop.title': '언제든 판매 중단 가능',
    'uniqdata.benefits.stop.desc': '원하지 않으면 언제든 NFT 발행과 판매를 중단할 수 있습니다',
    'uniqdata.security.title': '철저한 보안',
    'uniqdata.security.anonymous.title': '완전한 익명화',
    'uniqdata.security.anonymous.desc': '개인을 식별할 수 있는 모든 정보를 제거합니다',
    'uniqdata.security.blockchain.title': '블록체인 암호화',
    'uniqdata.security.blockchain.desc': '해킹이 불가능한 블록체인 기술로 보호합니다',
    'uniqdata.security.ownership.title': 'NFT 소유권 증명',
    'uniqdata.security.ownership.desc': 'XRPL NFT로 데이터 열람권 소유를 증명합니다',
    'uniqdata.cta.title': '데이터 지키고, 수익도 창출',
    'uniqdata.cta.desc': 'UniQdata와 함께 의료 데이터의 진정한 가치를 실현하세요',
    'uniqdata.cta.button': 'uniqdata.io 방문하기',

    // Qtech Page
    'qtech.research.ai.title': 'AI 헬스케어',
    'qtech.research.ai.desc': '딥러닝 기반 건강 예측 및 진단 보조 시스템',
    'qtech.research.ai.item1': '질병 조기 진단 AI',
    'qtech.research.ai.item2': '맞춤형 건강 관리 추천',
    'qtech.research.ai.item3': '의료 영상 분석',
    'qtech.research.iot.title': '스마트 홈 IoT',
    'qtech.research.iot.desc': '고령자 친화적 스마트 홈 환경 구축',
    'qtech.research.iot.item1': '낙상 감지 시스템',
    'qtech.research.iot.item2': '생활 패턴 분석',
    'qtech.research.iot.item3': '환경 자동 제어',
    'qtech.research.robot.item1': '대화형 AI 반려 로봇',
    'qtech.research.robot.item2': '복약 알림 로봇',
    'qtech.research.robot.item3': '긴급 상황 감지 및 알림',
    'qtech.research.blockchain.item1': '의료 데이터 익명화',
    'qtech.research.blockchain.item2': '스마트 컨트랙트 기반 보험',
    'qtech.research.blockchain.item3': '데이터 소유권 증명',
    'qtech.innovation.title': '혁신 프로세스',
    'qtech.innovation.research': '연구 개발',
    'qtech.innovation.research.desc': '최신 기술 연구',
    'qtech.innovation.prototype': '프로토타입',
    'qtech.innovation.prototype.desc': '실험 및 검증',
    'qtech.innovation.commercial': '상용화',
    'qtech.innovation.commercial.desc': '서비스 적용',
    'qtech.cta.button': '연구 파트너 되기',

    // XRPL Page
    'xrpl.hero.title': '건강 데이터 소유권과 수익화를 위한\nXRPL 기반 플랫폼',
    'xrpl.hero.desc': 'SportiQue는 XRPL 블록체인을 활용하여 건강 데이터의 소유권을\n사용자에게 돌려주고\n데이터 제공에 대한 공정한 보상을 제공하는 플랫폼입니다.',
    'xrpl.problem.title': '문제점',
    'xrpl.problem.ownership': '건강 데이터 소유권 문제',
    'xrpl.problem.ownership.desc': '사용자가 자신의 건강 데이터에 대한 통제권이 없음',
    'xrpl.problem.privacy': '개인정보 보호 취약',
    'xrpl.problem.privacy.desc': '중앙화된 시스템에서 데이터 유출 위험',
    'xrpl.problem.value': '데이터 가치 보상 부족',
    'xrpl.problem.value.desc': '데이터 제공에 대한 공정한 보상 체계 부재',
    'xrpl.problem.access': '데이터 접근성과 투명성 부족',
    'xrpl.problem.access.desc': '데이터 사용 내역 추적 불가능',
    'xrpl.solution.title': '해결책',
    'xrpl.solution.user.title': '사용자 중심 데이터 소유권',
    'xrpl.solution.user.desc': '블록체인 기반으로 사용자가 자신의 건강 데이터를 완전히 통제',
    'xrpl.solution.security.title': 'NFT 기술 기반 정보 보안 강화',
    'xrpl.solution.security.desc': 'NFT를 통한 데이터 접근 권한 관리 및 보안 강화',
    'xrpl.solution.monetization.title': 'XRP를 통한 데이터 수익화',
    'xrpl.solution.monetization.desc': '데이터 제공 시 XRP로 즉시 보상 지급',
    'xrpl.solution.model.title': '개별 구독 + 데이터 풀 모델',
    'xrpl.solution.model.desc': '기업 구독 및 데이터 풀 참여를 통한 다양한 수익 모델',
    'xrpl.use.title': 'XRPL 활용',
    'xrpl.use.escrow.title': 'TokenEscrow',
    'xrpl.use.escrow.desc': '기업이 지불한 XRP를 에스크로에 안전하게 보관하고 사용자가 데이터를 제공할 때마다 자동 보상 지급',
    'xrpl.use.mint.title': 'NFTokenMint',
    'xrpl.use.mint.desc': '구독 및 데이터 풀 참여에 대한 증명으로 NFT를 발행 후 데이터 접근 권한 관리',
    'xrpl.use.batch.title': 'Batch',
    'xrpl.use.batch.desc': '여러 개의 XRPL 트랜잭션을 묶어서 한번에 보내 기업이나 연구 기관에서 dataset을 구성할 수 있는 서비스 구축',
    'xrpl.use.memo.title': '트랜잭션 메모',
    'xrpl.use.memo.desc': '모든 데이터 접근과 보상 지급에 메모를 포함하여 감사 추적이 가능하고 투명한 거래 기록 유지',
    'xrpl.b2b2c.title': 'B2B2C 구조',
    'xrpl.b2b2c.business.title': '기업 (B)',
    'xrpl.b2b2c.business.item1': '개인 데이터 활용',
    'xrpl.b2b2c.business.item2': '비용 지불',
    'xrpl.b2b2c.business.item3': '신뢰 데이터 공급원',
    'xrpl.b2b2c.platform.title': '플랫폼 (B)',
    'xrpl.b2b2c.platform.name': 'SportiQue',
    'xrpl.b2b2c.platform.item1': '데이터 주권 보장',
    'xrpl.b2b2c.platform.item2': '투명성 보장',
    'xrpl.b2b2c.platform.item3': '보상 지급',
    'xrpl.b2b2c.consumer.title': '개인 (C)',
    'xrpl.b2b2c.consumer.item1': '건강 데이터 기록',
    'xrpl.b2b2c.consumer.item2': '개인 데이터 제공',
    'xrpl.b2b2c.consumer.item3': '보상 수령',
    'xrpl.roadmap.title': '로드맵',
    'xrpl.roadmap.2025q4.period': '2025년 4분기',
    'xrpl.roadmap.2025q4.title': '베타 출시 및 초기 사용자 확보',
    'xrpl.roadmap.2025q4.desc': 'XRPL 테스트넷 기반 베타 서비스 출시 및 초기 사용자 그룹 구축',
    'xrpl.roadmap.2026q2.period': '2026년 2분기',
    'xrpl.roadmap.2026q2.title': '메인넷 마이그레이션 및 기업 파트너십',
    'xrpl.roadmap.2026q2.desc': 'XRPL 메인넷 이전 및 첫 번째 기업 파트너십 체결, 데이터 풀 확장',
    'xrpl.roadmap.2026q4.period': '2026년 4분기',
    'xrpl.roadmap.2026q4.title': '데이터 마켓플레이스 출시',
    'xrpl.roadmap.2026q4.desc': '건강 데이터 NFT 거래 마켓플레이스 출시 및 데이터 유형 확장',
    'xrpl.roadmap.2027q2.period': '2027년 2분기',
    'xrpl.roadmap.2027q2.title': '글로벌 확장 및 API 생태계',
    'xrpl.roadmap.2027q2.desc': '글로벌 시장 진출 및 개발자 API 생태계 구축, 데이터 분석 도구 제공',
    'xrpl.roadmap.2028.period': '2028년',
    'xrpl.roadmap.2028.title': '건강 데이터 표준화 및 생태계 확장',
    'xrpl.roadmap.2028.desc': '글로벌 건강 데이터 표준화 주도 및 의료 기관 통합 확대',

    // Scaleup Page
    'scaleup.cta.woorijib.age': '30대',
    'scaleup.cta.woorijib.title': '우리집 알아보기',
    'scaleup.cta.woorijib.desc': '접근성 연구 프로젝트',
    'scaleup.cta.eoullim.age': '50-60대',
    'scaleup.cta.eoullim.title': '어울림 가입하기',
    'scaleup.cta.eoullim.desc': '건강한 인생 2막',
    'scaleup.cta.bodab.age': '60-70대',
    'scaleup.cta.bodab.title': 'Bodab 시작하기',
    'scaleup.cta.bodab.desc': '자립적 건강 관리',
    'scaleup.cta.nest.age': '70대+',
    'scaleup.cta.nest.title': 'Nest 알아보기',
    'scaleup.cta.nest.desc': '전문 케어 시스템',
    'scaleup.cta.uniqdata.age': '전 연령',
    'scaleup.cta.uniqdata.title': 'UniQdata 시작하기',
    'scaleup.cta.uniqdata.desc': '데이터로 수익 창출',
    'scaleup.lifecycle.title': '생애 전주기 케어 플랫폼',
    'scaleup.lifecycle.step1.title': '30대: 가족 소통의 시작',
    'scaleup.lifecycle.step1.desc': '우리집으로 가족 간 소통을 시작하고, 부모님의 건강 데이터를 관리합니다.',
    'scaleup.lifecycle.step2.title': '50-60대: 건강한 인생 2막',
    'scaleup.lifecycle.step2.desc': '어울림에서 또래와 함께 운동하며 건강한 노후를 준비합니다.',
    'scaleup.lifecycle.step3.title': '60-70대: 자립적 건강 관리',
    'scaleup.lifecycle.step3.desc': 'Bodab의 AI 헬스케어로 스스로 건강을 관리합니다.',
    'scaleup.lifecycle.step4.title': '70대+: 전문적인 케어',
    'scaleup.lifecycle.step4.desc': 'Nest에서 24시간 전문적인 케어를 받으며 편안한 노후를 보냅니다.',
    'scaleup.lifecycle.step5.title': '전 연령: 데이터 가치 실현',
    'scaleup.lifecycle.step5.desc': 'UniQdata로 의료 데이터를 안전하게 관리하고 수익을 창출합니다.',
    'scaleup.final.title': '한 번 시작하면 평생 함께',
    'scaleup.final.desc': 'SportiQue는 가족의 모든 세대와 함께 성장하며,\n각 시기에 필요한 최적의 헬스케어 솔루션을 제공합니다.',
    'scaleup.final.button': '서비스 둘러보기',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.woorijib': 'Woorijib',
    'nav.eoullim': 'Eoullim',
    'nav.bodab': 'Bodab',
    'nav.nest': 'Nest',
    'nav.uniqdata': 'UniQdata',
    'nav.qtech': 'Q-Tech',
    'nav.vision': 'Vision',

    // Q-Tech Page
    'qtech.title': 'Q-Tech',
    'qtech.subtitle': 'Where SportiQue\'s Future is Made',
    'qtech.description': 'Researching new care paradigms\nwith AI, IoT, and blockchain technology',
    'qtech.achievement': '2025 Hanium Dream Up - Care Robot Development Completed',
    'qtech.mission': 'Our Mission',
    'qtech.mission.statement': 'Enabling all generations to live healthier and happier lives through technology',
    'qtech.research': 'Main Research Areas',
    'qtech.research.robot': 'Care Robot',
    'qtech.research.robot.desc': 'Smart companion robot for elderly care',
    'qtech.research.blockchain': 'Blockchain',
    'qtech.research.blockchain.desc': 'Secure health data management based on XRPL',
    'qtech.cta.title': 'Big Changes from Small Technology',
    'qtech.cta.desc': 'Researching technology that makes life easier for the elderly',

    // Home Page
    'home.hero.title.line1': 'Connecting All Generations',
    'home.hero.title.line2': 'with Healthy Bonds',
    'home.hero.subtitle.line1': 'From 20s to 80s, providing the most appropriate care',
    'home.hero.subtitle.line2': 'when each generation needs it most',
    'home.services.title': 'Age-Tailored Solutions',
    'home.eoullim.age': '50s-60s',
    'home.eoullim.title': 'Eoullim',
    'home.eoullim.subtitle': 'Second Act of Life',
    'home.eoullim.feature1': 'Exercise with peers',
    'home.eoullim.feature2': 'Hobbies and clubs',
    'home.eoullim.feature3': 'Healthy lifestyle',
    'home.bodab.age': '60s-70s',
    'home.bodab.title': 'Bodab',
    'home.bodab.subtitle': 'Health Management',
    'home.bodab.feature1': 'Voice interface',
    'home.bodab.feature2': 'Medication reminders',
    'home.bodab.feature3': 'AI health consultation',
    'home.nest.age': '70+',
    'home.nest.title': 'Nest',
    'home.nest.subtitle': 'Professional Care',
    'home.nest.feature1': '24/7 professional care',
    'home.nest.feature2': 'Real-time family communication',
    'home.nest.feature3': 'Transparent care records',
    'home.uniqdata.title': 'Get Your Hospital Bills Back',
    'home.uniqdata.subtitle': 'Don\'t let your medical expenses go to waste.\nSell data access NFTs and create income.',
    'home.uniqdata.age': 'All Ages',
    'home.uniqdata.powered': 'Powered by XRPL',
    'home.uniqdata.platform': 'XRPL-based Medical Data NFT Marketplace',
    'home.uniqdata.desc': 'Issue access rights as NFTs for secure trading',
    'home.uniqdata.feature1': 'Store medical checkup data securely in UniQdata database',
    'home.uniqdata.feature2': 'Issue data access rights as XRPL NFTs',
    'home.uniqdata.feature3': 'Sell access NFTs to pharma & research institutions, earn XRP',
    'home.uniqdata.feature4': 'Data stays secure, only access rights are traded',
    'home.vision.title': 'Lifetime Care Platform',
    'home.vision.subtitle': 'A lifelong family health partner.\nProviding the most appropriate care when each generation needs it.',
    'home.vision.step1.title': '50s-60s: Healthy Second Act',
    'home.vision.step1.desc': 'Prepare for a healthy retirement by exercising with peers at Eoullim.',
    'home.vision.step2.title': '60s-70s: Independent Health Management',
    'home.vision.step2.desc': 'Manage your health independently with Bodab\'s AI healthcare.',
    'home.vision.step3.title': '70+: Professional Care',
    'home.vision.step3.desc': 'Enjoy comfortable retirement with 24/7 professional care at Nest.',
    'home.vision.step4.title': 'All Ages: Data Value Realization',
    'home.vision.step4.desc': 'Securely manage medical data and generate revenue with UniQdata.',

    // Woorijib Page
    'woorijib.title': 'Woorijib',
    'woorijib.subtitle': 'A Special Space for Families',
    'woorijib.desc': 'Research project for accessibility improvement\nExploring new paradigms in family communication',

    // Eoullim Page
    'eoullim.title': 'Eoullim',
    'eoullim.subtitle': 'A Special Space for Life\'s Second Act',
    'eoullim.desc': 'Premium fitness & social club for those in their 50s-60s\nHealthy body and mind, and new friends',

    // Nest Page
    'nest.title': 'Nest',
    'nest.subtitle': 'Warm Home, Professional Care',
    'nest.desc': 'Premium care facility for seniors 70+\nTransparent care system with family',

    // Vision Page
    'vision.title': 'The Family We Envision',
    'vision.subtitle': 'The hearts of children worried about their parents,\nThe hearts of parents not wanting to be a burden,\nWe understand both hearts.',
    'vision.cta': 'Start Now',
    'vision.cta.desc': 'Choose a service tailored to your age',

    // Hero Section
    'hero.title.line1': 'Building a Healthy Future',
    'hero.title.line2': 'with Two Services from Sportique',
    'hero.subtitle.line1': 'Experience AI healthcare with Bodab',
    'hero.subtitle.line2': 'and realize data sovereignty with UniqData',
    'hero.cta.start': 'Get Started',
    'hero.cta.learn': 'Learn More',

    // Features Section
    'features.title': 'Core Features of Bodab',
    'features.subtitle': 'Innovative healthcare solutions powered by AI and blockchain',
    'features.step': 'STEP',
    'features.1.title': 'AI Health Analysis',
    'features.1.desc': 'RAG-based AI analyzes past medical records to provide personalized health consultations',
    'features.2.title': 'Real-time Monitoring',
    'features.2.desc': 'Monitor vital signs 24/7 through wearable devices and IoT',
    'features.3.title': 'Blockchain Security',
    'features.3.desc': 'Securely store health data on XRPL network and guarantee ownership',
    'features.4.title': 'Data Monetization',
    'features.4.desc': 'Receive instant rewards in XRP when providing health data',

    // About Section
    'about.title': 'About Sportique',
    'about.ecosystem': 'Sportique\'s Integrated Healthcare Ecosystem',
    'about.ecosystem.desc': 'Health data collected from Bodab connects to UniqData to realize data sovereignty and monetization. AI healthcare meets blockchain technology to create a healthy global society.',
    'about.check1': 'AI-based senior care solution (Bodab)',
    'about.check2': 'Global data marketplace (UniqData)',
    'about.check3': 'XRPL blockchain-based data security',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'Creating a healthy digital society where everyone owns their health data and receives fair compensation from it.',

    // Services Section
    'services.title': 'Our Services',
    'services.subtitle': 'Two independent services provided by Sportique',
    'services.bodab.title': 'Bodab',
    'services.bodab.desc': 'AI-based senior healthcare app providing personalized senior care through data measurement and health analysis',
    'services.bodab.feature1': 'AI Health Analysis',
    'services.bodab.feature2': 'Real-time Data Measurement',
    'services.bodab.feature3': 'Senior Care Solution',
    'services.bodab.cta': 'Learn More',
    'services.uniqdata.title': 'UniqData',
    'services.uniqdata.desc': 'Global data marketplace realizing health data sovereignty and monetization through NFTs and zero-knowledge proofs',
    'services.uniqdata.feature1': 'Data Sovereignty Realization',
    'services.uniqdata.feature2': 'NFT-based Ownership Proof',
    'services.uniqdata.feature3': 'Data Monetization',
    'services.uniqdata.cta': 'Visit UniqData',

    // Rewards Section
    'rewards.title': 'Bodab',
    'rewards.desc': 'AI-based senior healthcare app providing personalized senior care through data measurement and health analysis',
    'rewards.connection': 'Collected health data is transmitted to UniqData to become the foundation for data sovereignty and monetization',
    'rewards.feature1.title': 'AI Health Analysis',
    'rewards.feature1.desc': 'RAG-based medical consultation, past medical record analysis, personalized health recommendations',
    'rewards.feature2.title': 'Real-time Data Measurement',
    'rewards.feature2.desc': 'Wearable device integration, 24/7 vital signs monitoring, health status tracking',
    'rewards.feature3.title': 'Senior Care Solution',
    'rewards.feature3.desc': 'Customized care for aging society, emergency response, family peace of mind service',
    'rewards.cta': 'Learn More',

    // XRPL Section
    'xrpl.title': 'UniqData Global Marketplace',
    'xrpl.desc': 'At uniqdata.io, realize sovereignty over health data collected from Bodab, and create revenue from your data through data anonymization, transfer, and sales via NFTs and zero-knowledge proofs',
    'xrpl.connection': 'Health data generated from Bodab is securely managed and monetized on UniqData',
    'xrpl.feature1': 'Health data sovereignty realization',
    'xrpl.feature2': 'NFT-based data ownership proof',
    'xrpl.feature3': 'Anonymization through zero-knowledge proofs',
    'xrpl.feature4': 'Revenue generation through data transfer and sales',
    'xrpl.cta': 'Visit UniqData',
    'xrpl.card.title': 'UniqData.io',
    'xrpl.card.subtitle': 'Global Data Marketplace',

    // Partners Section
    'partners.title': 'Partnerships',
    'partners.subtitle': 'Building an innovative healthcare ecosystem together',
    'partners.hoseo.name': 'Hoseo University',
    'partners.hoseo.type': 'Academic Partner',
    'partners.hoseo.desc': 'AI healthcare research collaboration',
    'partners.xrpl.name': 'XRPL Foundation',
    'partners.xrpl.type': 'Technology Partner',
    'partners.xrpl.desc': 'Blockchain technology support',
    'partners.medical.name': 'Medical Institutions',
    'partners.medical.type': 'Medical Partner',
    'partners.medical.desc': 'Medical data integration',
    'partners.wearable.name': 'Wearable Companies',
    'partners.wearable.type': 'Hardware Partner',
    'partners.wearable.desc': 'IoT device integration',
    'partners.insurance.name': 'Insurance Companies',
    'partners.insurance.type': 'Business Partner',
    'partners.insurance.desc': 'Healthcare insurance linkage',
    'partners.government.name': 'Government Agencies',
    'partners.government.type': 'Policy Partner',
    'partners.government.desc': 'Digital healthcare policy',

    // Footer
    'footer.description': 'A platform that reclaims data sovereignty with XRPL-based blockchain technology and provides AI-based healthcare solutions.',
    'footer.services': 'Services',
    'footer.bodab': 'Bodab',
    'footer.uniqdata': 'UniqData',
    'footer.xrpl': 'XRPL',
    'footer.company': 'Company',
    'footer.about': 'About',
    'footer.careers': 'Careers',
    'footer.partnership': 'Partnership',
    'footer.support': 'Support',
    'footer.customer': 'Customer Service',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact Us',
    'footer.copyright': '© 2025 Sportique. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // Bodab Page
    'bodab.page.subtitle': 'Independent Health Management Platform for Seniors 60-70',
    'bodab.page.desc': 'Easy-to-use health management service with large text and voice interface',
    'bodab.features.title': 'Core Features of Bodab',
    'bodab.features.voice.title': 'Voice Interface',
    'bodab.features.voice.desc': 'Use all features by voice without complex touches',
    'bodab.features.medication.title': 'Medication Management',
    'bodab.features.medication.desc': 'Automatically reminds medication times and manages records',
    'bodab.features.health.title': 'Health Records',
    'bodab.features.health.desc': 'Easily record and manage health metrics like blood pressure and blood sugar',
    'bodab.features.hospital.title': 'Hospital Appointments',
    'bodab.features.hospital.desc': 'Check medical appointments and hospital visit schedules at a glance',
    'bodab.features.family.title': 'Family Sharing',
    'bodab.features.family.desc': 'Safely share health information with family members',
    'bodab.features.sos.title': 'Emergency SOS',
    'bodab.features.sos.desc': 'Quickly request help in emergency situations',
    'bodab.ai.title': 'AI Health Assistant',
    'bodab.ai.desc': '24/7 AI health assistant takes care of senior health.',
    'bodab.ai.consultation.title': 'Health Consultation',
    'bodab.ai.consultation.desc': 'AI provides appropriate advice when you describe symptoms',
    'bodab.ai.conversation.title': 'Daily Conversation',
    'bodab.ai.conversation.desc': 'Always available as a conversation partner when you feel lonely',
    'bodab.ai.coaching.title': 'Health Habit Coaching',
    'bodab.ai.coaching.desc': 'Helps you build healthy lifestyle habits',
    'bodab.ai.quote1': '"Did you take your medicine today?"',
    'bodab.ai.quote2': '"It\'s time to check your blood pressure"',
    'bodab.simple.title': 'Simple and Easy to Use',
    'bodab.simple.large.title': 'Large Text',
    'bodab.simple.large.desc': 'All text is large and clear for easy reading',
    'bodab.simple.voice.title': 'Voice Commands',
    'bodab.simple.voice.desc': 'Control everything by voice',
    'bodab.simple.simple.title': 'Simple Layout',
    'bodab.simple.simple.desc': 'Only essential features arranged large and clear',
    'bodab.cta.title': 'When Health Management is Needed, Independent Care',
    'bodab.cta.desc': 'Manage your healthy retirement independently with Bodab',
    'bodab.cta.button': 'Start Free Trial',

    // Nest Page
    'nest.features.title': 'What Makes Nest Special',
    'nest.features.care24.title': '24/7 Professional Care',
    'nest.features.care24.desc': 'Medical staff and caregivers are on-site 24/7 to care for seniors',
    'nest.features.family.title': 'Real-time Family Communication',
    'nest.features.family.desc': 'Daily care reports and video calls keep families connected',
    'nest.features.home.title': 'Warm Home',
    'nest.features.home.desc': 'Live in a safe and comfortable environment like home',
    'nest.features.record.title': 'Transparent Care Records',
    'nest.features.record.desc': 'All care activities are transparently recorded and shared with family',
    'nest.system.title': 'Professional Care System',
    'nest.system.medical.title': 'On-site Medical Staff',
    'nest.system.medical.desc': 'Professional medical staff monitor health status 24/7',
    'nest.system.custom.title': 'Customized Care Plans',
    'nest.system.custom.desc': 'Provides personalized care tailored to individual health conditions',
    'nest.system.rehab.title': 'Rehabilitation Programs',
    'nest.system.rehab.desc': 'Professional rehabilitation programs to help health recovery',
    'nest.system.emotional.title': 'Emotional Care',
    'nest.system.emotional.desc': 'Various programs provide emotional stability',
    'nest.system.quote1': 'Warm Home',
    'nest.system.quote2': 'Professional Care',
    'nest.cta.title': 'The Best Choice for Parents',
    'nest.cta.desc': 'Gift your parents a comfortable and happy retirement with Nest',
    'nest.cta.button': 'Request Consultation',

    // Eoullim Page
    'eoullim.programs.title': 'Customized Programs',
    'eoullim.programs.yoga.title': 'Senior Yoga',
    'eoullim.programs.yoga.desc': 'Gentle movements that improve flexibility and balance without joint strain',
    'eoullim.programs.aqua.title': 'Aquarobics',
    'eoullim.programs.aqua.desc': 'Full-body workout in water, minimizing joint burden',
    'eoullim.programs.walking.title': 'Walking Group',
    'eoullim.programs.walking.desc': 'Healthy walking exercise together in the neighborhood park',
    'eoullim.programs.dance.title': 'Dance Class',
    'eoullim.programs.dance.desc': 'Silver dance with joyful music',
    'eoullim.programs.strength.title': 'Strength Training',
    'eoullim.programs.strength.desc': 'Strength building program using safe equipment',
    'eoullim.programs.meditation.title': 'Meditation & Stretching',
    'eoullim.programs.meditation.desc': 'Healing program to find balance of mind and body',
    'eoullim.community.title': 'Community Together',
    'eoullim.community.desc': 'Exercise with peers, make new friends, and build healthy lifestyle habits.',
    'eoullim.community.trainer': 'Safe guidance from professional trainers',
    'eoullim.community.custom': 'Age-appropriate exercise programs',
    'eoullim.community.tea': 'Healthy tea gathering after exercise',
    'eoullim.community.check': 'Monthly health check and consultation',
    'eoullim.community.quote': 'Start a healthy second act of life',
    'eoullim.cta.title': 'Start a Healthy Second Act of Life',
    'eoullim.cta.desc': '50% off the first month when you join now',
    'eoullim.cta.button': 'Request Free Trial',

    // Woorijib Page
    'woorijib.features.title': 'Key Features',
    'woorijib.features.messenger.title': 'Family-Only Messenger',
    'woorijib.features.messenger.desc': 'Clean family communication space without ads',
    'woorijib.features.album.title': 'Auto Album Organization',
    'woorijib.features.album.desc': 'AI automatically organizes photos and videos',
    'woorijib.features.schedule.title': 'Family Schedule Sharing',
    'woorijib.features.schedule.desc': 'Manage important family schedules together',
    'woorijib.features.parent.title': 'Parent Mode',
    'woorijib.features.parent.desc': 'Large text and simple interface',
    'woorijib.features.health.title': 'Health Check',
    'woorijib.features.health.desc': 'Check family members\' health status',
    'woorijib.features.privacy.title': 'Privacy Protection',
    'woorijib.features.privacy.desc': 'Safe protection of family data',
    'woorijib.cta.title': 'Accessibility Improvement Research Project',
    'woorijib.cta.desc': 'Creating the new future of family communication together',
    'woorijib.cta.button': 'Join Project',

    // UniqData Page
    'uniqdata.page.title': 'XRPL-based Medical Data NFT Marketplace',
    'uniqdata.page.desc': 'Store data securely and issue access rights as NFTs for trading',
    'uniqdata.page.powered': 'Powered by XRPL',
    'uniqdata.features.title': 'UniQdata\'s Innovative Features',
    'uniqdata.features.storage.title': 'Secure Data Storage',
    'uniqdata.features.storage.desc': 'Safely store medical data in UniQdata DB',
    'uniqdata.features.nft.title': 'Access Rights NFT Issuance',
    'uniqdata.features.nft.desc': 'Issue data access rights as XRPL NFTs to prove ownership',
    'uniqdata.features.revenue.title': 'NFT Sales Revenue',
    'uniqdata.features.revenue.desc': 'Sell access NFTs to pharmaceutical companies and research institutes, earn XRP',
    'uniqdata.how.title': 'How Does It Work?',
    'uniqdata.how.step1.title': 'Data Storage',
    'uniqdata.how.step1.desc': 'Securely store medical data in UniQdata database',
    'uniqdata.how.step2.title': 'NFT Issuance',
    'uniqdata.how.step2.desc': 'Issue data access rights as XRPL NFTs',
    'uniqdata.how.step3.title': 'NFT Sales',
    'uniqdata.how.step3.desc': 'Sell access NFTs to pharmaceutical companies and research institutes',
    'uniqdata.how.step4.title': 'XRP Revenue',
    'uniqdata.how.step4.desc': 'Instantly settle NFT sales in XRP',
    'uniqdata.benefits.title': 'The Era Where Data Becomes Money',
    'uniqdata.benefits.desc': 'Your medical data that you\'ve been providing for free,\nNow get fair compensation through UniQdata.',
    'uniqdata.benefits.transparent.title': 'Transparent NFT Trading',
    'uniqdata.benefits.transparent.desc': 'All NFT transactions are transparently recorded on XRPL blockchain',
    'uniqdata.benefits.safe.title': 'Data Stored Safely',
    'uniqdata.benefits.safe.desc': 'Original data is safely stored in UniQdata DB, only access rights are traded',
    'uniqdata.benefits.instant.title': 'Instant Settlement System',
    'uniqdata.benefits.instant.desc': 'When NFTs are sold, instant settlement in XRP',
    'uniqdata.benefits.stop.title': 'Stop Sales Anytime',
    'uniqdata.benefits.stop.desc': 'You can stop NFT issuance and sales anytime if you don\'t want to',
    'uniqdata.security.title': 'Thorough Security',
    'uniqdata.security.anonymous.title': 'Complete Anonymization',
    'uniqdata.security.anonymous.desc': 'Remove all personally identifiable information',
    'uniqdata.security.blockchain.title': 'Blockchain Encryption',
    'uniqdata.security.blockchain.desc': 'Protected by unhackable blockchain technology',
    'uniqdata.security.ownership.title': 'NFT Ownership Proof',
    'uniqdata.security.ownership.desc': 'Prove data access rights ownership with XRPL NFTs',
    'uniqdata.cta.title': 'Protect Data and Generate Revenue',
    'uniqdata.cta.desc': 'Realize the true value of medical data with UniQdata',
    'uniqdata.cta.button': 'Visit uniqdata.io',

    // Qtech Page
    'qtech.research.ai.title': 'AI Healthcare',
    'qtech.research.ai.desc': 'Deep learning-based health prediction and diagnostic support system',
    'qtech.research.ai.item1': 'Early disease diagnosis AI',
    'qtech.research.ai.item2': 'Personalized health management recommendations',
    'qtech.research.ai.item3': 'Medical image analysis',
    'qtech.research.iot.title': 'Smart Home IoT',
    'qtech.research.iot.desc': 'Building elderly-friendly smart home environment',
    'qtech.research.iot.item1': 'Fall detection system',
    'qtech.research.iot.item2': 'Life pattern analysis',
    'qtech.research.iot.item3': 'Automatic environment control',
    'qtech.research.robot.item1': 'Conversational AI companion robot',
    'qtech.research.robot.item2': 'Medication reminder robot',
    'qtech.research.robot.item3': 'Emergency detection and alerts',
    'qtech.research.blockchain.item1': 'Medical data anonymization',
    'qtech.research.blockchain.item2': 'Smart contract-based insurance',
    'qtech.research.blockchain.item3': 'Data ownership proof',
    'qtech.innovation.title': 'Innovation Process',
    'qtech.innovation.research': 'Research & Development',
    'qtech.innovation.research.desc': 'Latest technology research',
    'qtech.innovation.prototype': 'Prototype',
    'qtech.innovation.prototype.desc': 'Testing and validation',
    'qtech.innovation.commercial': 'Commercialization',
    'qtech.innovation.commercial.desc': 'Service application',
    'qtech.cta.button': 'Become a Research Partner',

    // XRPL Page
    'xrpl.hero.title': 'XRPL-Based Platform for Health Data\nOwnership and Monetization',
    'xrpl.hero.desc': 'SportiQue returns health data ownership\nto users using XRPL blockchain\nand provides fair compensation for data provision.',
    'xrpl.problem.title': 'Problems',
    'xrpl.problem.ownership': 'Health Data Ownership Issue',
    'xrpl.problem.ownership.desc': 'Users have no control over their own health data',
    'xrpl.problem.privacy': 'Weak Privacy Protection',
    'xrpl.problem.privacy.desc': 'Data breach risk in centralized systems',
    'xrpl.problem.value': 'Lack of Data Value Compensation',
    'xrpl.problem.value.desc': 'No fair compensation system for data provision',
    'xrpl.problem.access': 'Lack of Data Accessibility and Transparency',
    'xrpl.problem.access.desc': 'Unable to track data usage history',
    'xrpl.solution.title': 'Solutions',
    'xrpl.solution.user.title': 'User-Centric Data Ownership',
    'xrpl.solution.user.desc': 'Users have complete control over their health data based on blockchain',
    'xrpl.solution.security.title': 'NFT Technology-Based Information Security Enhancement',
    'xrpl.solution.security.desc': 'Data access rights management and security enhancement through NFTs',
    'xrpl.solution.monetization.title': 'Data Monetization Through XRP',
    'xrpl.solution.monetization.desc': 'Instant rewards in XRP when providing data',
    'xrpl.solution.model.title': 'Individual Subscription + Data Pool Model',
    'xrpl.solution.model.desc': 'Various revenue models through corporate subscriptions and data pool participation',
    'xrpl.use.title': 'XRPL Utilization',
    'xrpl.use.escrow.title': 'TokenEscrow',
    'xrpl.use.escrow.desc': 'Safely store XRP paid by companies in escrow and automatically reward users when they provide data',
    'xrpl.use.mint.title': 'NFTokenMint',
    'xrpl.use.mint.desc': 'Issue NFTs as proof of subscription and data pool participation, then manage data access rights',
    'xrpl.use.batch.title': 'Batch',
    'xrpl.use.batch.desc': 'Bundle multiple XRPL transactions to send at once, building dataset services for companies or research institutions',
    'xrpl.use.memo.title': 'Transaction Memo',
    'xrpl.use.memo.desc': 'Include memos in all data access and reward payments to enable audit trails and maintain transparent transaction records',
    'xrpl.b2b2c.title': 'B2B2C Structure',
    'xrpl.b2b2c.business.title': 'Business (B)',
    'xrpl.b2b2c.business.item1': 'Utilize personal data',
    'xrpl.b2b2c.business.item2': 'Pay costs',
    'xrpl.b2b2c.business.item3': 'Trusted data source',
    'xrpl.b2b2c.platform.title': 'Platform (B)',
    'xrpl.b2b2c.platform.name': 'SportiQue',
    'xrpl.b2b2c.platform.item1': 'Guarantee data sovereignty',
    'xrpl.b2b2c.platform.item2': 'Ensure transparency',
    'xrpl.b2b2c.platform.item3': 'Distribute rewards',
    'xrpl.b2b2c.consumer.title': 'Individual (C)',
    'xrpl.b2b2c.consumer.item1': 'Record health data',
    'xrpl.b2b2c.consumer.item2': 'Provide personal data',
    'xrpl.b2b2c.consumer.item3': 'Receive rewards',
    'xrpl.roadmap.title': 'Roadmap',
    'xrpl.roadmap.2025q4.period': 'Q4 2025',
    'xrpl.roadmap.2025q4.title': 'Beta Launch and Early User Acquisition',
    'xrpl.roadmap.2025q4.desc': 'Launch beta service based on XRPL testnet and build initial user group',
    'xrpl.roadmap.2026q2.period': 'Q2 2026',
    'xrpl.roadmap.2026q2.title': 'Mainnet Migration and Corporate Partnership',
    'xrpl.roadmap.2026q2.desc': 'XRPL mainnet migration and first corporate partnership, data pool expansion',
    'xrpl.roadmap.2026q4.period': 'Q4 2026',
    'xrpl.roadmap.2026q4.title': 'Data Marketplace Launch',
    'xrpl.roadmap.2026q4.desc': 'Launch health data NFT trading marketplace and expand data types',
    'xrpl.roadmap.2027q2.period': 'Q2 2027',
    'xrpl.roadmap.2027q2.title': 'Global Expansion and API Ecosystem',
    'xrpl.roadmap.2027q2.desc': 'Global market entry and developer API ecosystem building, data analysis tools',
    'xrpl.roadmap.2028.period': '2028',
    'xrpl.roadmap.2028.title': 'Health Data Standardization and Ecosystem Expansion',
    'xrpl.roadmap.2028.desc': 'Lead global health data standardization and expand medical institution integration',

    // Scaleup Page
    'scaleup.cta.woorijib.age': '30s',
    'scaleup.cta.woorijib.title': 'Learn About Woorijib',
    'scaleup.cta.woorijib.desc': 'Accessibility Research Project',
    'scaleup.cta.eoullim.age': '50s-60s',
    'scaleup.cta.eoullim.title': 'Join Eoullim',
    'scaleup.cta.eoullim.desc': 'Healthy Second Act',
    'scaleup.cta.bodab.age': '60s-70s',
    'scaleup.cta.bodab.title': 'Start Bodab',
    'scaleup.cta.bodab.desc': 'Independent Health Management',
    'scaleup.cta.nest.age': '70+',
    'scaleup.cta.nest.title': 'Learn About Nest',
    'scaleup.cta.nest.desc': 'Professional Care System',
    'scaleup.cta.uniqdata.age': 'All Ages',
    'scaleup.cta.uniqdata.title': 'Start UniQdata',
    'scaleup.cta.uniqdata.desc': 'Monetize Your Data',
    'scaleup.lifecycle.title': 'Lifetime Care Platform',
    'scaleup.lifecycle.step1.title': '30s: Start of Family Communication',
    'scaleup.lifecycle.step1.desc': 'Start family communication with Woorijib and manage parents\' health data.',
    'scaleup.lifecycle.step2.title': '50s-60s: Healthy Second Act',
    'scaleup.lifecycle.step2.desc': 'Prepare for healthy retirement by exercising with peers at Eoullim.',
    'scaleup.lifecycle.step3.title': '60s-70s: Independent Health Management',
    'scaleup.lifecycle.step3.desc': 'Manage your health independently with Bodab\'s AI healthcare.',
    'scaleup.lifecycle.step4.title': '70+: Professional Care',
    'scaleup.lifecycle.step4.desc': 'Enjoy comfortable retirement with 24/7 professional care at Nest.',
    'scaleup.lifecycle.step5.title': 'All Ages: Data Value Realization',
    'scaleup.lifecycle.step5.desc': 'Securely manage medical data and generate revenue with UniQdata.',
    'scaleup.final.title': 'Together for Life Once Started',
    'scaleup.final.desc': 'SportiQue grows with all generations of the family,\nproviding optimal healthcare solutions for each stage.',
    'scaleup.final.button': 'Explore Services',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language');
    return (savedLanguage === 'ko' || savedLanguage === 'en') ? savedLanguage : 'ko';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ko']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};