import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
const data=JSON.parse(readFileSync('assets/public-records.json','utf8'));
const assetVersion=createHash('sha256').update(readFileSync('assets/neon-site-20260921.css')).update(readFileSync('assets/neon-site-20260921.js')).digest('hex').slice(0,12);
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const arrow='<span aria-hidden="true">↗</span>';
const login='https://org.sportique.biz/products/uniqlab';
const routes=[['/','홈'],['/products/','제품'],['/about/','회사'],['/founder/','대표'],['/awards/','이력'],['/contact/','문의']];
const emblem=`<div class="brand-emblem" data-brand-emblem role="img" aria-label="SportiQue의 S 말풍선 입체 로고"><img class="emblem-static" src="/assets/sportique-emblem-fallback.svg" alt="" width="420" height="420"><canvas class="logo-canvas" aria-hidden="true"></canvas></div>`;
function header(path){const links=routes.map(([url,name])=>`<a href="${url}" ${path===url?'aria-current="page"':''}>${name}</a>`).join('');return `<a class="skip-link" href="#main">본문으로 이동</a><header class="site-header"><a class="brand original-brand" href="/" aria-label="SportiQue 홈"><img src="/assets/sportique-icon.jpg" alt="SportiQue" width="82" height="82"></a><nav class="desktop-nav" aria-label="주 메뉴">${links}</nav><div class="header-actions"><a class="institution-login" href="${login}">기관 로그인 ${arrow}</a><details class="mobile-menu"><summary aria-label="전체 메뉴 열기"><span></span><span></span></summary><nav aria-label="모바일 메뉴">${links}<a href="/institutions/">기관 포털 안내</a></nav></details></div></header>`;}
const footer=`<footer class="site-footer"><div class="footer-brand"><a class="original-brand" href="/" aria-label="SportiQue 홈"><img src="/assets/sportique-icon.jpg" alt="SportiQue" width="150" height="150" loading="lazy"></a><p>내 건강기록을,<br>내가 선택한 곳에서.</p></div><nav aria-label="추가 정보">${routes.slice(1).map(([url,name])=>`<a href="${url}">${name}</a>`).join('')}<a href="/institutions/">기관 포털</a></nav><div class="footer-bottom"><span>© 2026 SportiQue. All rights reserved.</span><a href="mailto:daniel@sportique.biz">daniel@sportique.biz</a><span>Personal health data network</span></div></footer>`;
function pageHero(kicker,title,description,ghost){return `<section class="page-hero"><div class="page-marker" aria-hidden="true">${ghost}</div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p class="page-lead">${description}</p></section>`;}
const cta=`<section class="closing-cta"><p class="eyebrow">LET’S MAKE IT MATTER</p><h2>다음 이야기는,<br><em>함께.</em></h2><a class="filled-link" href="/contact/">SportiQue에 연락하기 ${arrow}</a></section>`;
// Only provenance-reviewed source media belong here; hardware media keeps its design-review boundary.
const media={
 uniqdata:`<figure class="product-media app-media"><img src="/assets/verified/uniqdata-home-dev-20260916.png" alt="개별 데이터 보기, 건강 데이터 연결, 오늘의 기록이 보이는 UniQdata 개발 화면" loading="lazy"><figcaption>UniQdata · 개발 화면의 테스트 데이터</figcaption></figure>`,
 uniqlab:`<figure class="product-media desktop-media"><img src="/assets/verified/uniqlab-screen-20260922.png" alt="UniQLab 연구 허브에서 진행 연구와 다음 작업을 보여주는 검증용 데모 화면" loading="lazy"><figcaption>UniQLab · 검증용 데모 화면</figcaption></figure>`,
 bodab:`<figure class="product-media app-media"><img src="/assets/verified/bodab-screen-20260922.png" alt="Bodab Build 6 오늘 화면에서 복약 상태와 아침 체크인, 일정을 보여주는 앱 화면" loading="lazy"><figcaption>Bodab · Build 6 앱 화면</figcaption></figure>`,
 yakson:`<div class="device-media"><figure class="product-media device-study-media"><img src="/assets/verified/yakson-evt-v3-frame-20260916.png" alt="YAKSON 개방형 V3 기구의 디지털 검토 화면. 연결 약포 롤, 이송부와 전면 수령부가 보입니다." loading="lazy"><figcaption>2026.09 개방형 기구 V3 · 디지털 검토본</figcaption></figure><details class="model-preview"><summary>현재 기구 동작 검토 보기 <span aria-hidden="true">＋</span></summary><video controls playsinline preload="none" aria-label="YAKSON 하단 보관 및 다음 회차 제시 경로의 디지털 검토 영상"><source src="/assets/verified/yakson-evt-v3-preview-20260916.mp4" type="video/mp4">브라우저에서 영상을 지원하지 않습니다. <a href="/assets/verified/yakson-evt-v3-preview-20260916.mp4">디지털 검토 영상 열기</a></video><p>미수령 약포를 하단에 보관하고 다음 회차 한 봉을 제시하는 경로를 살핀 디지털 후보입니다. 완성 외관·실물 반복 작동·제조 적합성은 검증 전입니다.</p></details></div>`
};
const productCards=data.products.map((p,i)=>`<article class="product-panel product-${p.id}" id="${p.id}"><div class="product-panel-copy"><span class="index-number">0${i+1} / ${esc(p.label)}</span><h2>${esc(p.name)}</h2><p class="product-description">${esc(p.description)}</p><p>${esc(p.detail)}</p><ul class="feature-list">${p.features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul>${p.modules.length?`<p class="product-modules">${p.modules.map(esc).join(' · ')}</p>`:''}<a class="text-link" href="${esc(p.href)}">${p.href==='/contact'?'제품 문의하기':p.name+' 알아보기'} ${arrow}</a>${p.id==='uniqlab'?'<p class="product-consent">개인이 연구 참여와 공유 범위를 선택한 뒤 연결되는 활용처입니다.</p>':''}</div>${media[p.id]}</article>`).join('');
// Unknown days remain unknown in the display; ranges sort by their ending date.
function dateKey({date,sortDate}){
 if(date==='현재')return sortDate??Infinity;
 const value=String(sortDate??date);
 if(/^\d{8}$/.test(value))return Number(value);
 const range=value.split(value.includes('.')?/[-~–—]/:/[~–—]/);
 const start=(range[0].match(/\d+/g)??[]).map(Number);
 const end=(range.at(-1).match(/\d+/g)??[]).map(Number);
 const parts=end[0]>=1000?end:end.length===1&&start.length===3?[...start.slice(0,2),...end]:[start[0],...end];
 return (parts[0]||0)*10000+(parts[1]||0)*100+(parts[2]||0);
}
const latestFirst=(a,b)=>dateKey(b)-dateKey(a);
const founderItems=[...data.founder].sort(latestFirst).map((r,i)=>`<article class="record-item" id="founder-${i}"><div class="record-date">${esc(r.date)}</div><div><h3>${esc(r.title)}</h3><p class="record-meta">${esc(r.meta)}</p><p>${esc(r.body)}</p></div><span class="record-index">${String(i+1).padStart(2,'0')}</span></article>`).join('');
const awardLabels={award:'수상',selected:'선정',presentation:'발표',fieldwork:'해외 활동',company:'회사 연혁'};
const awardCategory=r=>r.category||(/수상|상$/.test(r.title)?'award':/선정/.test(r.title)?'selected':'presentation');
const awardsRecords=[...data.awards].sort(latestFirst);
const awardCategories=[...new Set(awardsRecords.map(awardCategory))];
const awardFilters=awardCategories.map(category=>`<button type="button" data-filter="${esc(category)}" aria-pressed="false">${esc(awardLabels[category]??category)} ${awardsRecords.filter(r=>awardCategory(r)===category).length}</button>`).join('');
function awardEvidence(record){
 const evidence=record.evidence;if(!evidence)return '';
 const image=evidence.image?`<figure class="award-proof-image"><img src="${esc(evidence.image)}" alt="${esc(evidence.imageAlt)}" loading="lazy" decoding="async"><figcaption>${esc(evidence.imageLabel)}</figcaption></figure>`:'';
 const links=(evidence.links??[]).map(link=>`<a class="award-proof-link" href="${esc(link.href)}" target="_blank" rel="noopener noreferrer">${esc(link.label)} ${arrow}</a>`).join('');
 return `<div class="award-evidence">${image}${links?`<div class="award-proof-links">${links}</div>`:''}</div>`;
}
const awardsItems=awardsRecords.map((r,i)=>{const category=awardCategory(r);const datetime=r.date.replaceAll('.','-');return `<article class="timeline-event" data-category="${esc(category)}" id="award-${i}"><time${/^\d{4}-\d{2}(?:-\d{2})?$/.test(datetime)?` datetime="${datetime}"`:''}>${esc(r.date)}</time><div class="timeline-body${r.evidence?' has-evidence':''}"><div class="award-copy"><span class="award-kind">${esc(awardLabels[category]??category)}</span><h3>${esc(r.title)}</h3><p class="record-meta">${esc(r.organizer)}</p>${r.venue?`<p class="award-venue">${esc(r.venue)}</p>`:''}<p>${esc(r.body)}</p></div>${awardEvidence(r)}</div></article>`;}).join('');
const founderAwards=`<div class="founder-awards"><p class="eyebrow">SELECTED AWARDS / 주요 수상</p><ul>${awardsRecords.filter(r=>r.founderHighlight).map(r=>`<li class="founder-award"><span>${esc(r.date)}</span><div><strong>${esc(r.title)}</strong><small>${esc(r.founderHighlight)}</small></div></li>`).join('')}</ul><a class="text-link" href="/awards/">전체 수상·선정 이력 ${arrow}</a></div>`;
const pages=[
 {path:'/',title:'파편화된 건강데이터를 개인의 데이터베이스로',description:'파편화된 건강데이터를 개인이 직접 관리하고, 공유 범위와 AI 모델·플랫폼을 선택할 수 있는 기반. SportiQue.',body:readFileSync('scripts/home-content.html','utf8').replaceAll('{{EMBLEM}}',emblem)},
 {path:'/products/',title:'Products — 기록이 일상이 되는 곳',description:'UniQdata, UniQLab, Bodab, YAKSON. 개인의 건강기록에서 일상과 돌봄, 동의한 연구로 이어지는 제품.',body:pageHero('THE THINGS WE BUILD','기록이<br><em>일상이 되는 곳.</em>','개인의 기록을 모으는 일부터, 가족의 하루를 챙기는 일까지.<br>각자의 자리에서 연결되는 네 가지 제품.','PRODUCTS')+`<section class="product-universe">${productCards}</section>`+cta},
 {path:'/about/',title:'About — 개인에게 돌아오는 주도권',description:'SportiQue의 돌봄에서 출발한 문제의식과 개인의 건강데이터 통제 원칙.',body:pageHero('OUR REASON TO BUILD','돌봄에서 시작한 질문.<br><em>개인에게 돌아오는 답.</em>','누군가를 더 잘 돌보려면, 그 사람의 하루를 더 잘 이해해야 합니다.<br>SportiQue는 기록이 필요한 사람의 손에 닿도록 연결합니다.','ABOUT')+`<section class="manifesto-grid"><div class="about-emblem">${emblem}<span class="emblem-wordmark">SportiQue</span></div><div><p class="eyebrow">THE INDIVIDUAL, FIRST</p><h2>주도권을<br><em>기업에서 개인으로.</em></h2><p>건강기록은 병원, 기기, 일상과 연구 현장에 흩어져 있습니다. SportiQue는 그 기록이 개인을 중심으로 쌓이고, 필요한 순간에 쓰일 수 있는 구조를 만듭니다.</p><p>누구에게, 어떤 목적으로, 어디까지, 언제까지 공유할지 개인이 결정합니다. 연구기관은 여러 활용처 중 하나이며, 그 시작은 UniQdata입니다.</p></div></section><section class="principles-list"><article><span>01 / STORE</span><h3>나의 기록을, 한곳에.</h3><p>출처가 다른 원본을 모으고 확인합니다. DataQ가 원본과 출처를 보존하면서 형식·항목·단위를 표준화하고, 개인이 확인한 기록은 개인 DB로 이어집니다.</p></article><article><span>02 / USE</span><h3>기록을, 나의 일상에.</h3><p>기록을 읽고 이해하는 일에서 진료 준비와 일상 루틴까지. 개인이 자기 기록을 활용하는 경험을 연결합니다.</p></article><article><span>03 / CHOOSE</span><h3>공유의 결정도, 내가 직접.</h3><p>공유 대상·목적·범위·기간을 개인이 정합니다. 동의·철회와 접근·이용 이력을 확인할 수 있는 구조를 만듭니다.</p></article></section><section class="history-statement"><p class="eyebrow">OUR FOUNDATION / 2025</p><h2>기록의 권한을<br><em>기술로 구현한 경험.</em></h2><p>2025년 XRPL 데모에서는 사용자가 공유 범위와 열람 기간을 직접 정하고, 접근·활용 이력을 확인하며 연구 참여 보상이 자동 처리되는 흐름을 구현했습니다. 건강기록 원문은 개인 DB에 두었습니다.</p><a class="text-link" href="/awards/">수상·선정·발표 기록 ${arrow}</a></section><section class="company-facts"><div><small>COMPANY</small><b>SportiQue · 스포티큐</b></div><div><small>FOUNDER</small><b>SeungHun Lee</b></div><div><small>STARTING POINT</small><b>UniQdata</b></div><div><small>OUR FOCUS</small><b>Personal health data</b></div></section>`+cta},
 {path:'/founder/',title:'Founder — SeungHun Lee',description:'SportiQue 이승헌 대표의 제품·기술 방향과 공개 교육·연구·프로그램 이력.',body:`<section class="founder-hero"><div class="founder-heading"><p class="eyebrow">THE PERSON BEHIND SPORTIQUE</p><h1>SeungHun<br><em>Lee.</em></h1><p>이승헌 · Founder, CEO &amp; CTO</p><span class="founder-signature">BUILD. CONNECT. CARE.</span>${founderAwards}</div><figure class="founder-portrait"><img src="/assets/verified/founder-portrait-retouched-20260923.jpg" alt="SportiQue 이승헌 대표 프로필 사진" fetchpriority="high"><figcaption>이승헌 · SportiQue</figcaption></figure></section><section class="founder-statement"><p class="eyebrow">PRODUCT × TECHNOLOGY</p><div><h2>문제를 이해하고,<br>제품을 직접<br><em>만듭니다.</em></h2><p>SportiQue의 제품 방향과 앱·서버·AI 구현, 기관 협업을 이끌고 있습니다. UniQdata, UniQLab, Bodab, YAKSON을 각각의 사용자와 현장에 맞는 건강데이터 경험으로 연결합니다.</p><a class="text-link" href="mailto:daniel@sportique.biz">daniel@sportique.biz ${arrow}</a></div></section><section class="records-section"><div class="section-heading"><div><p class="eyebrow">EDUCATION / RESEARCH / EXPERIENCE</p><h2>쌓아온 경험.</h2></div><a class="text-link" href="/awards/">회사 수상·선정 이력 ${arrow}</a></div><p class="section-subtitle">대표 개인의 교육, 자격, 논문 발표와 프로젝트 참여 이력입니다.</p>${founderItems}</section>`+cta},
 {path:'/awards/',title:'Milestones — 우리가 걸어온 길',description:'SportiQue 수상·선정·발표, 해외 활동과 회사 연혁을 최신순으로 읽는 타임라인.',body:pageHero('MILESTONES / LATEST FIRST','오늘에 가까운 순간부터.<br><em>우리가 걸어온 길.</em>','수상과 선정, 발표와 현장.<br>최근의 기록에서 처음의 도전까지 내려가며 만납니다.','TIMELINE')+`<section class="awards-section"><div class="award-filters" aria-label="이력 분류"><button type="button" data-filter="all" aria-pressed="true">전체</button>${awardFilters}<span id="record-count" aria-live="polite">공개 기록 ${awardsRecords.length}건</span></div><div class="awards-timeline">${awardsItems}</div></section>`+cta},
 {path:'/contact/',title:'Contact — 다음 이야기는, 함께',description:'SportiQue 제품, 돌봄 현장, 기관·연구 협업 문의.',body:pageHero('A CONVERSATION STARTS HERE','어떤 연결을<br><em>만들고 싶으세요?</em>','제품에 대한 질문도, 현장에서 만난 문제도 좋습니다.<br>당신의 이야기를 들려주세요.','HELLO')+`<section class="contact-editorial"><div class="contact-address"><p class="eyebrow">TALK TO SPORTIQUE</p><a href="mailto:daniel@sportique.biz">daniel<span>@sportique.biz</span>${arrow}</a><p>제품 · 파트너십 · 기관 및 연구 협업</p></div><div class="contact-options"><a href="mailto:daniel@sportique.biz?subject=SportiQue%20협업%20문의"><span>01</span><div><h2>함께 만들고 싶어요.</h2><p>기관·연구 협업, 현장 적용과 제품 파트너십</p></div>${arrow}</a><a href="mailto:support@sportique.biz"><span>02</span><div><h2>제품을 사용하고 있어요.</h2><p>UniQdata · UniQLab · Bodab · YAKSON 이용 문의</p></div>${arrow}</a><a href="https://org.sportique.biz/onboarding"><span>03</span><div><h2>기관에 도입하고 싶어요.</h2><p>기관 정보와 필요한 제품으로 도입 절차 시작하기</p></div>${arrow}</a></div></section>`},
 {path:'/institutions/',title:'Institutions — 기관 포털',description:'기존 UniQLab 기관 계정 로그인과 SportiQue 신규 기관 도입을 연결합니다.',body:pageHero('INSTITUTION ACCESS','기관의 다음 업무,<br><em>여기서 이어갑니다.</em>','이미 개통된 계정은 로그인으로.<br>새로운 협업은 기관 도입 신청으로 시작하세요.','ACCESS')+`<section class="access-grid"><article class="access-card primary-access"><p class="eyebrow">EXISTING INSTITUTION</p><h2>기관 계정 로그인</h2><p>개통된 UniQLab 기관 직원 계정으로 연구자 초대, 기관 연구와 예산 운영을 이어갑니다.</p><a class="filled-link" href="${login}">UniQLab 기관 로그인 ${arrow}</a><small>기관 이메일·비밀번호로 인증하며, 필요한 경우 추가 인증을 진행합니다.</small></article><article class="access-card"><p class="eyebrow">NEW INSTITUTION</p><h2>새로운 기관 도입</h2><p>대학교·연구기관·병원·체육기관·기업. 필요한 제품을 선택하고 기관 도입 절차를 시작합니다.</p><a class="outline-link" href="https://org.sportique.biz/onboarding">기관 도입 신청 ${arrow}</a><small>기관 확인과 제품별 계정 개통은 별도로 진행됩니다.</small></article></section><section class="access-note"><div><span class="eyebrow">ONE HUB. DISTINCT ROLES.</span><h2>내 역할에 맞는 공간.</h2></div><div><p>기관 운영 계정과 개인 연구자 계정은 역할이 다릅니다. 개인 연구자로 접속하려면 연구 워크스페이스를 이용하세요.</p><a class="text-link" href="https://web.uniqlab.io/">연구 워크스페이스 ${arrow}</a><a class="text-link" href="mailto:support@sportique.biz">기관 계정 지원 문의 ${arrow}</a></div></section>`},
 {path:'/404.html',title:'404 — 새로운 경로로',description:'요청한 페이지를 찾을 수 없습니다. SportiQue 홈과 제품으로 이동하세요.',body:pageHero('SIGNAL LOST / 404','길을 잃었나요?<br><em>다시 연결합니다.</em>','요청한 페이지가 없거나 주소가 바뀌었습니다.','404')+`<section class="not-found-actions"><a class="filled-link" href="/">홈으로 돌아가기 ${arrow}</a><a class="outline-link" href="/products/">제품 보기 ${arrow}</a></section>`}
];
for(const p of pages){const output=p.path==='/'?'index.html':p.path==='/404.html'?'404.html':p.path.slice(1)+'index.html';if(output.includes('/'))mkdirSync(output.slice(0,output.lastIndexOf('/')),{recursive:true});writeFileSync(output,`<!doctype html>\n<html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(p.description)}"><meta name="theme-color" content="#050609"><meta property="og:title" content="SportiQue — ${esc(p.title)}"><meta property="og:description" content="${esc(p.description)}"><meta property="og:image" content="https://www.sportique.biz/assets/sportique-header.jpg"><link rel="canonical" href="https://www.sportique.biz${p.path}"><link rel="icon" href="/assets/sportique-icon.jpg"><title>SportiQue — ${esc(p.title)}</title><link rel="stylesheet" href="/assets/neon-site-20260921.css?v=${assetVersion}"><script type="module" src="/assets/neon-site-20260921.js?v=${assetVersion}"></script></head><body data-page="${p.path==='/'?'home':esc(p.path)}"><div class="ambient-glow" aria-hidden="true"></div>${header(p.path)}<main id="main">${p.body}</main>${footer}</body></html>\n`);}
console.log(`Built ${pages.length} public pages; preserved ${data.founder.length} founder and ${data.awards.length} award records.`);
